version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: psdbase
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  product_service:
    build: .
    container_name: product_service
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mynetwork
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/psdbase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Rome
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  mynetwork: