services:
  - type: web
    name: product-service
    env: docker
    buildCommand: ./mvnw package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SPRING_PROFILES_ACTIVE
        value: prod

databases:
  - name: postgres
    ipAllowList: []