services:
  - type: web
    name: product-service
    env: docker
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: PGUSER
        fromDatabase:
          name: postgres
          property: username
      - key: PGPASSWORD
        fromDatabase:
          name: postgres
          property: password
      - key: PGHOST
        fromDatabase:
          name: postgres
          property: host
      - key: PGPORT
        value: "5432"
      - key: PGDATABASE
        fromDatabase:
          name: postgres
          property: database
      - key: SPRING_PROFILES_ACTIVE
        value: prod

databases:
  - name: postgres
    ipAllowList: []