services:
  - type: web
    name: product-service
    env: docker
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: PGUSER
        fromDatabase:
          name: postgres
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: postgres
          property: password
      - key: PGHOST
        fromDatabase:
          name: postgres
          property: host
      - key: PGDATABASE
        fromDatabase:
          name: postgres
          property: database
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

databases:
  - name: postgres
    ipAllowList: []